ansible_connection: ansible.netcommon.network_cli
ansible_network_os: cisco.ios.ios
ansible_become: true
ansible_become_method: enable
ansible_timeout: 60
ansible_command_timeout: 60
ansible_persistent_command_timeout: 60
ansible_user: svc-ansible
ansible_ssh_private_key_file: /root/.ssh/id_rsa_cisco
